### ISSUE TITLE
Move media to other collections / OK-Button does not work

### ISSUE THREAD

**Issue by andreasganahl** [sulu/sulu#2858]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Sulu Version | 1.2.3
| Browser Version | Browser name and version

#### Actual Behavior

by moving medias to other collections two functions are available for choosing the new collection.
1. choose the collection with the "checkmarker" > works
2. choose the collection and the button "OK" > does not work

#### Expected Behavior

Booth possibilities should work, or only one possibility should be available

#### Steps to Reproduce

Move media elements to other collections

#### Possible Solutions

reduce to one possibility to move media?

**Comment by danrot** [comment]
The OK button is completely missing in the move page dialog. It should be introduced there as well, and it should of course work in both move dialogs.

**Comment by danrot** [comment]
Fixed in https://github.com/sulu/sulu/pull/2876

**Comment by andreasganahl** [comment]
Problem is not solved:
2. choose the collection and the button "OK" > does not work

**Comment by danrot** [comment]
The issue has been solved in a different way: You have to click on the tick appearing when hovering the page AND press the OK button. This behavior was discussed like that with @berndhep, so I'll close this issue again.
