### ISSUE TITLE
Media-Selection param types

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/sulu#537]
Refactor to collection (current comma seperated list).

Dont forget to update documentation: https://github.com/sulu-cmf/docs/blob/master/developer-documentation/500-assets/media-selection.md

**Comment by danrot** [comment]
@wachterjohannes I guess this is already fixed, there are no comma separated list in the documentation

**Comment by wachterjohannes** [comment]
@danrot sorry but that is not fixed you can read under https://github.com/sulu-cmf/docs/blob/master/developer-documentation/500-assets/media-selection.md#params that the types are comma-seperated

**Comment by wachterjohannes** [comment]
seems to be no problem until now so i will close this issue
