### ISSUE TITLE
Using `%kernel.debug%` in the SuluHttpCache configuration

### ISSUE THREAD

**Issue by arjanfrans** [sulu/sulu#5823]
| Q | A
| --- | ---
| Sulu Version | 2.2.3
| PHP Version | 7.4.14
| DB Version | 8.0.23
| Browser Version | Chromium 88

# Actual Behavior
I am using the `kernel.debug` parameter in my `sulu_http_cache` config. This however results in an error because it requires an actual boolean.

```
sulu_http_cache:
    debug:
        enabled: "%kernel.debug%"
```

```
Invalid type for path "sulu_http_cache.debug.enabled". Expected "bool", but got "string".
Hint: Whether to send a debug header with the response to trigger a caching proxy to send debug information. If not set, defaults to kernel.debug.
```

# Expected Behavior

Just like many other Symfony bundles, I'd like to be able to use the `kernel.debug` parameter to enable/disable debugging easily for the `sulu_http_cache`

# Steps to Reproduce

Configure the http cache like this:

```
sulu_http_cache:
    debug:
        enabled: "%kernel.debug%"
```

# Possible Solutions

Allow the value to be a string and cast it during the configuration parsing.

**Comment by alexander-schranz** [comment]
@arjanfrans Thx for report. It seems like the parameter is  not correctly resolved when set manually to `%kernel.debug%`. 

But in case of `sulu_http_cache` the `kernel.debug` flag is used as default for debug enabled or disabled so it don't need to be set manually: https://github.com/sulu/sulu/blob/466edcb9beb7debe5c64e75bade7d04bbb6164de/src/Sulu/Bundle/HttpCacheBundle/DependencyInjection/Configuration.php#L97.

**Comment by alexander-schranz** [comment]
I find out that this is caused in the PrependExtension but not sure if its on our side or the Symfony side bug with PrependExtension. I created a issue there https://github.com/symfony/symfony/issues/40198 and hope I get some feedback soon.

**Comment by arjanfrans** [comment]
I have the same problem with some other options, for example:

![image](https://user-images.githubusercontent.com/3588470/109321399-64936f00-7851-11eb-9128-b7e70cd86478.png)

The same applies probably to `tags.enabled`, `proxy_client.enabled` and possibly other boolean configuration values in SULU?

**Comment by alexander-schranz** [comment]
@arjanfrans thx for report think its here a general issue with parameter in the resolving process. Sadly got not yet any Feedback from symfony as for me it look like its implement the same was as in there docs, but in that example no parameters where used.

**Comment by arjanfrans** [comment]
@alexander-schranz If Symfony is not going to solve this anytime soon, do you see another way to solve it within Sulu?

**Comment by alexander-schranz** [comment]
@arjanfrans could find a way to resolve the values but will wait for the feedback of the [symfony team](https://github.com/symfony/symfony-docs/pull/15048/files), if this is the correct way to handle this. At current state I would in your case use `stage` and `prod` environment and configure it the specific values directly instead of depend on `%kernel.debug%` value here.

**Comment by niklasnatter** [comment]
Should be fixed in #5854 - thanks for reporting!

**Comment by arjanfrans** [comment]
https://github.com/sulu/sulu/issues/5823#issuecomment-786723758

My parameter '%enable_varnish%' is resolved from an environment variable, '%env(bool:ENABLE_VARNISH)%'

This still doesn't work because it doesn't resolve it to a boolean:

```
!!    Invalid type for path "sulu_http_cache.proxy_client.varnish.enabled". Expec  
!!    ted "bool", but got "string".
```

@alexander-schranz

**Comment by niklasnatter** [comment]
@arjanfrans What version of the `sulu/sulu` package is installed in your project?

**Comment by arjanfrans** [comment]
> @arjanfrans What version of the `sulu/sulu` package is installed in your project?

@nnatter 2.2.6

**Comment by alexander-schranz** [comment]
@arjanfrans I think symfony env vars are not build to be used this way to enable or disable things which have effects how the  container is build and I think thats why my previous issue was ignored by the Symfony Team. Currently you could workaround this issue by creating a kernel parameter in your `Kernel.php` e.g.:

```php
    protected function getKernelParameters()
    {
        return \array_merge(
            [
                'enable_varnish' => \filter_var($_ENV['VARNISH_ENABLED'], FILTER_VALIDATE_BOOLEAN),
            ],
            parent::getKernelParameters()
        );
    }
```

**Comment by nnatter** [comment]
Sorry, I have not noticed that you are trying to set the value of the parameter via an environment variable. There is an intentional distinction between environment variables and parameters and when to use one vs. the other in Symfony (see https://speakerdeck.com/nicolasgrekas/configuring-symfony-from-localhost-to-high-availability). I could imagine that what you are trying to do is indeed not supported by Symfony.

**Comment by niklasnatter** [comment]
@arjanfrans Sorry, I have not noticed that you are trying to set the value of the parameter via an environment variable. There is an intentional distinction between environment variables and parameters and when to use one vs. the other in Symfony (see https://speakerdeck.com/nicolasgrekas/configuring-symfony-from-localhost-to-high-availability). 
I could imagine that what you are trying to do is indeed not supported by the way Symfony handles this.

**Comment by niklasnatter** [comment]
@arjanfrans This new issue might be interesting for your case too: https://github.com/symfony/symfony/issues/40794
